#!/bin/sh
set -eu

: "${AI_SERVER_ADVERTISE_ADDRESS:?AI_SERVER_ADVERTISE_ADDRESS is required}"
: "${NACOS_SERVER_ADDRESSES:?NACOS_SERVER_ADDRESSES is required}"
: "${NACOS_USERNAME:?NACOS_USERNAME is required}"
: "${NACOS_PASSWORD:?NACOS_PASSWORD is required}"
: "${CAT_COLLECTOR_ADDRESSES:?CAT_COLLECTOR_ADDRESSES is required}"

: "${AI_SERVER_INSTANCE_ID:=fiber-ai-server}"
: "${AUDIT_INGEST_TOKEN:=}"
: "${AUDIT_HTTP_QUEUE_CAPACITY_BYTES:=16777216}"
: "${AUDIT_HTTP_BATCH_SIZE:=100}"
: "${AUDIT_HTTP_BATCH_MAX_BYTES:=8388608}"
: "${AUDIT_HTTP_FLUSH_INTERVAL_MS:=250}"
: "${AUDIT_HTTP_CONNECT_TIMEOUT_MS:=2000}"
: "${AUDIT_HTTP_REQUEST_TIMEOUT_MS:=10000}"
export AI_SERVER_INSTANCE_ID AUDIT_INGEST_TOKEN AUDIT_HTTP_QUEUE_CAPACITY_BYTES AUDIT_HTTP_BATCH_SIZE
export AUDIT_HTTP_BATCH_MAX_BYTES AUDIT_HTTP_FLUSH_INTERVAL_MS AUDIT_HTTP_CONNECT_TIMEOUT_MS
export AUDIT_HTTP_REQUEST_TIMEOUT_MS

if [ "${AI_SERVER_AUDIT_TRANSPORT:-HTTP}" = "HTTP" ]; then
  : "${AUDIT_INGEST_TOKEN:?AUDIT_INGEST_TOKEN is required for HTTP audit transport}"
fi

envsubst < /etc/ai-server/ai-server.env.template > /tmp/ai-server.env
chmod 0600 /tmp/ai-server.env
exec /usr/local/bin/ai-server /tmp/ai-server.env
