export const userModuleMigration = {
  id: '001-user-module',
  statements: [
    `CREATE TABLE IF NOT EXISTS schema_migrations (
      id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      applied_at DATETIME(6) NOT NULL,
      PRIMARY KEY (id)
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4`,
    `CREATE TABLE IF NOT EXISTS environments (
      id BINARY(16) NOT NULL,
      name VARCHAR(128) NOT NULL,
      stage VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      revision BIGINT UNSIGNED NOT NULL DEFAULT 1,
      created_at DATETIME(6) NOT NULL,
      updated_at DATETIME(6) NOT NULL,
      PRIMARY KEY (id),
      CONSTRAINT chk_environments_stage CHECK (stage IN ('development', 'staging', 'production'))
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4`,
    `CREATE TABLE IF NOT EXISTS users (
      id BINARY(16) NOT NULL,
      username VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
      display_name VARCHAR(128) NOT NULL,
      email VARCHAR(254) NULL,
      system_role VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      auth_provider VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      external_subject VARBINARY(255) NOT NULL,
      revision BIGINT UNSIGNED NOT NULL DEFAULT 1,
      last_login_at DATETIME(6) NULL,
      created_at DATETIME(6) NOT NULL,
      updated_at DATETIME(6) NOT NULL,
      deleted_at DATETIME(6) NULL,
      PRIMARY KEY (id),
      UNIQUE KEY uq_users_username (username),
      UNIQUE KEY uq_users_auth_subject (auth_provider, external_subject),
      KEY idx_users_status_role (status, system_role, updated_at),
      CONSTRAINT chk_users_role CHECK (system_role IN ('USER', 'ADMIN')),
      CONSTRAINT chk_users_status CHECK (status IN ('PENDING', 'ACTIVE', 'SUSPENDED', 'DELETED')),
      CONSTRAINT chk_users_username_bytes CHECK (OCTET_LENGTH(username) BETWEEN 1 AND 64)
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4`,
    `CREATE TABLE IF NOT EXISTS environment_token_policies (
      environment_id BINARY(16) NOT NULL,
      self_service_enabled BOOLEAN NOT NULL DEFAULT FALSE,
      min_ttl_seconds INT UNSIGNED NOT NULL DEFAULT 300,
      default_ttl_seconds INT UNSIGNED NOT NULL DEFAULT 3600,
      max_ttl_seconds INT UNSIGNED NOT NULL DEFAULT 604800,
      max_active_tokens_per_user SMALLINT UNSIGNED NOT NULL DEFAULT 5,
      require_effective_key BOOLEAN NOT NULL DEFAULT TRUE,
      delivery_ttl_seconds SMALLINT UNSIGNED NOT NULL DEFAULT 300,
      revision BIGINT UNSIGNED NOT NULL DEFAULT 1,
      created_at DATETIME(6) NOT NULL,
      updated_at DATETIME(6) NOT NULL,
      PRIMARY KEY (environment_id),
      CONSTRAINT chk_environment_policy_ttl CHECK (
        min_ttl_seconds >= 300
        AND min_ttl_seconds <= default_ttl_seconds
        AND default_ttl_seconds <= max_ttl_seconds
        AND max_ttl_seconds <= 2592000
      ),
      CONSTRAINT chk_environment_policy_count CHECK (max_active_tokens_per_user BETWEEN 0 AND 20),
      CONSTRAINT chk_environment_policy_delivery CHECK (delivery_ttl_seconds BETWEEN 60 AND 600),
      CONSTRAINT fk_environment_policy_environment
        FOREIGN KEY (environment_id) REFERENCES environments (id)
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4`,
    `CREATE TABLE IF NOT EXISTS user_environment_access (
      user_id BINARY(16) NOT NULL,
      environment_id BINARY(16) NOT NULL,
      can_issue_tokens BOOLEAN NOT NULL DEFAULT TRUE,
      max_token_ttl_seconds INT UNSIGNED NULL,
      max_active_tokens SMALLINT UNSIGNED NULL,
      revision BIGINT UNSIGNED NOT NULL DEFAULT 1,
      granted_by BINARY(16) NOT NULL,
      created_at DATETIME(6) NOT NULL,
      updated_at DATETIME(6) NOT NULL,
      revoked_at DATETIME(6) NULL,
      PRIMARY KEY (user_id, environment_id),
      KEY idx_user_environment_environment (environment_id, revoked_at, user_id),
      CONSTRAINT fk_user_environment_user FOREIGN KEY (user_id) REFERENCES users (id),
      CONSTRAINT fk_user_environment_environment FOREIGN KEY (environment_id) REFERENCES environments (id),
      CONSTRAINT fk_user_environment_granted_by FOREIGN KEY (granted_by) REFERENCES users (id)
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4`,
    `CREATE TABLE IF NOT EXISTS user_sessions (
      id BINARY(16) NOT NULL,
      user_id BINARY(16) NOT NULL,
      session_token_hash BINARY(32) NOT NULL,
      csrf_token_hash BINARY(32) NOT NULL,
      auth_time DATETIME(6) NOT NULL,
      mfa_time DATETIME(6) NULL,
      created_at DATETIME(6) NOT NULL,
      last_seen_at DATETIME(6) NOT NULL,
      idle_expires_at DATETIME(6) NOT NULL,
      absolute_expires_at DATETIME(6) NOT NULL,
      revoked_at DATETIME(6) NULL,
      PRIMARY KEY (id),
      UNIQUE KEY uq_user_sessions_token_hash (session_token_hash),
      KEY idx_user_sessions_user_active (user_id, revoked_at, absolute_expires_at),
      KEY idx_user_sessions_expiry (absolute_expires_at, revoked_at),
      CONSTRAINT fk_user_sessions_user FOREIGN KEY (user_id) REFERENCES users (id)
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4`,
    `CREATE TABLE IF NOT EXISTS managed_secrets (
      id BINARY(16) NOT NULL,
      secret_kind VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      ciphertext TEXT CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      nonce VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      fingerprint BINARY(32) NOT NULL,
      created_at DATETIME(6) NOT NULL,
      updated_at DATETIME(6) NOT NULL,
      destroyed_at DATETIME(6) NULL,
      PRIMARY KEY (id),
      KEY idx_managed_secrets_kind (secret_kind, destroyed_at)
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4`,
    `CREATE TABLE IF NOT EXISTS bt1_signing_keys (
      id BINARY(16) NOT NULL,
      environment_id BINARY(16) NOT NULL,
      kid VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      secret_id BINARY(16) NOT NULL,
      key_state VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      issuance_enabled BOOLEAN NOT NULL DEFAULT FALSE,
      issuer_slot TINYINT GENERATED ALWAYS AS (
        CASE WHEN issuance_enabled = TRUE THEN 1 ELSE NULL END
      ) STORED,
      clock_skew_seconds SMALLINT UNSIGNED NOT NULL DEFAULT 0,
      retire_after DATETIME(6) NULL,
      revision BIGINT UNSIGNED NOT NULL DEFAULT 1,
      created_at DATETIME(6) NOT NULL,
      updated_at DATETIME(6) NOT NULL,
      PRIMARY KEY (id),
      UNIQUE KEY uq_bt1_signing_key_kid (environment_id, kid),
      UNIQUE KEY uq_bt1_signing_key_issuer (environment_id, issuer_slot),
      KEY idx_bt1_signing_key_state (environment_id, key_state, updated_at),
      CONSTRAINT chk_bt1_signing_key_state CHECK (
        key_state IN ('DRAFT', 'PUBLISHED_UNVERIFIED', 'ACTIVE', 'RETIRING', 'RETIRED')
      ),
      CONSTRAINT chk_bt1_signing_key_skew CHECK (clock_skew_seconds BETWEEN 0 AND 300),
      CONSTRAINT fk_bt1_signing_key_environment FOREIGN KEY (environment_id) REFERENCES environments (id),
      CONSTRAINT fk_bt1_signing_key_secret FOREIGN KEY (secret_id) REFERENCES managed_secrets (id)
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4`,
    `CREATE TABLE IF NOT EXISTS user_tokens (
      id BINARY(16) NOT NULL,
      user_id BINARY(16) NOT NULL,
      environment_id BINARY(16) NOT NULL,
      signing_key_id BINARY(16) NOT NULL,
      token_name VARCHAR(64) NOT NULL,
      token_fingerprint BINARY(32) NOT NULL,
      token_nonce VARCHAR(22) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      bt1_version VARCHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'BT1',
      kid VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      clock_skew_seconds SMALLINT UNSIGNED NOT NULL,
      issued_by BINARY(16) NOT NULL,
      issued_for_reason VARCHAR(500) NULL,
      issued_at DATETIME(6) NOT NULL,
      expires_at DATETIME(6) NOT NULL,
      accepted_until DATETIME(6) NOT NULL,
      disabled_at DATETIME(6) NULL,
      disabled_by BINARY(16) NULL,
      disable_reason VARCHAR(500) NULL,
      compromise_suspected BOOLEAN NOT NULL DEFAULT FALSE,
      last_used_at DATETIME(6) NULL,
      last_used_source VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NULL,
      created_at DATETIME(6) NOT NULL,
      updated_at DATETIME(6) NOT NULL,
      PRIMARY KEY (id),
      UNIQUE KEY uq_user_token_fingerprint (token_fingerprint),
      UNIQUE KEY uq_user_token_nonce (environment_id, kid, token_nonce),
      UNIQUE KEY uq_user_token_name (user_id, environment_id, token_name),
      KEY idx_user_tokens_owner (user_id, environment_id, expires_at),
      KEY idx_user_tokens_environment_expiry (environment_id, accepted_until, disabled_at),
      KEY idx_user_tokens_signing_key (signing_key_id, accepted_until),
      CONSTRAINT fk_user_tokens_access
        FOREIGN KEY (user_id, environment_id)
        REFERENCES user_environment_access (user_id, environment_id),
      CONSTRAINT fk_user_tokens_signing_key FOREIGN KEY (signing_key_id) REFERENCES bt1_signing_keys (id),
      CONSTRAINT fk_user_tokens_issued_by FOREIGN KEY (issued_by) REFERENCES users (id),
      CONSTRAINT fk_user_tokens_disabled_by FOREIGN KEY (disabled_by) REFERENCES users (id)
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4`,
    `CREATE TABLE IF NOT EXISTS token_deliveries (
      token_id BINARY(16) NOT NULL,
      session_id BINARY(16) NOT NULL,
      idempotency_key_hash BINARY(32) NOT NULL,
      request_hash BINARY(32) NOT NULL,
      ciphertext VARCHAR(2048) CHARACTER SET ascii COLLATE ascii_bin NULL,
      nonce VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
      created_at DATETIME(6) NOT NULL,
      expires_at DATETIME(6) NOT NULL,
      purged_at DATETIME(6) NULL,
      PRIMARY KEY (token_id),
      UNIQUE KEY uq_token_delivery_idempotency (session_id, idempotency_key_hash),
      KEY idx_token_delivery_expiry (expires_at, purged_at),
      CONSTRAINT fk_token_delivery_token FOREIGN KEY (token_id) REFERENCES user_tokens (id),
      CONSTRAINT fk_token_delivery_session FOREIGN KEY (session_id) REFERENCES user_sessions (id)
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4`,
    `CREATE TABLE IF NOT EXISTS audit_events (
      id BINARY(16) NOT NULL,
      sequence_no BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      actor_user_id BINARY(16) NULL,
      actor_role VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NULL,
      event_type VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      target_type VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      target_id BINARY(16) NULL,
      environment_id BINARY(16) NULL,
      correlation_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      reason VARCHAR(500) NULL,
      payload JSON NOT NULL,
      occurred_at DATETIME(6) NOT NULL,
      PRIMARY KEY (id),
      UNIQUE KEY uq_audit_sequence (sequence_no),
      KEY idx_audit_actor_time (actor_user_id, occurred_at),
      KEY idx_audit_target_time (target_type, target_id, occurred_at),
      KEY idx_audit_environment_time (environment_id, occurred_at),
      CONSTRAINT fk_audit_actor FOREIGN KEY (actor_user_id) REFERENCES users (id)
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4`,
    `CREATE TABLE IF NOT EXISTS security_invariants (
      lock_name VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      revision BIGINT UNSIGNED NOT NULL DEFAULT 1,
      updated_at DATETIME(6) NOT NULL,
      PRIMARY KEY (lock_name)
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4`,
    `INSERT IGNORE INTO security_invariants (lock_name, revision, updated_at)
      VALUES ('ACTIVE_ADMIN_GUARD', 1, '1970-01-01 00:00:00.000000')`,
  ],
} as const
