export const modelMarketplaceMigration = {
  id: '002-model-marketplace',
  statements: [
    `CREATE TABLE IF NOT EXISTS schema_migrations (
      id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      applied_at DATETIME(6) NOT NULL,
      PRIMARY KEY (id)
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4`,
    `CREATE TABLE IF NOT EXISTS configuration_versions (
      id BINARY(16) NOT NULL,
      environment_id BINARY(16) NOT NULL,
      version_kind VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      version_state VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      base_release_version_id BINARY(16) NULL,
      schema_version INT UNSIGNED NOT NULL DEFAULT 1,
      revision BIGINT UNSIGNED NOT NULL DEFAULT 1,
      created_by BINARY(16) NOT NULL,
      created_at DATETIME(6) NOT NULL,
      updated_at DATETIME(6) NOT NULL,
      frozen_at DATETIME(6) NULL,
      abandoned_at DATETIME(6) NULL,
      PRIMARY KEY (id),
      KEY idx_config_versions_environment (environment_id, version_kind, version_state, updated_at),
      CONSTRAINT chk_config_version_kind CHECK (version_kind IN ('DRAFT', 'RELEASE')),
      CONSTRAINT chk_config_version_state CHECK (version_state IN ('OPEN', 'FROZEN', 'ABANDONED')),
      CONSTRAINT chk_config_version_freeze CHECK (
        (version_state = 'FROZEN' AND frozen_at IS NOT NULL)
        OR (version_state <> 'FROZEN' AND frozen_at IS NULL)
      ),
      CONSTRAINT fk_config_version_environment FOREIGN KEY (environment_id) REFERENCES environments (id),
      CONSTRAINT fk_config_version_base_release FOREIGN KEY (base_release_version_id) REFERENCES configuration_versions (id),
      CONSTRAINT fk_config_version_created_by FOREIGN KEY (created_by) REFERENCES users (id)
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4`,
    `CREATE TABLE IF NOT EXISTS marketplace_models (
      id BINARY(16) NOT NULL,
      environment_id BINARY(16) NOT NULL,
      logical_model_name VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      created_by BINARY(16) NOT NULL,
      created_at DATETIME(6) NOT NULL,
      archived_by BINARY(16) NULL,
      archived_at DATETIME(6) NULL,
      PRIMARY KEY (id),
      UNIQUE KEY uq_marketplace_model_name (environment_id, logical_model_name),
      KEY idx_marketplace_models_environment (environment_id, archived_at, id),
      CONSTRAINT chk_marketplace_model_name_bytes CHECK (OCTET_LENGTH(logical_model_name) BETWEEN 1 AND 128),
      CONSTRAINT fk_marketplace_model_environment FOREIGN KEY (environment_id) REFERENCES environments (id),
      CONSTRAINT fk_marketplace_model_created_by FOREIGN KEY (created_by) REFERENCES users (id),
      CONSTRAINT fk_marketplace_model_archived_by FOREIGN KEY (archived_by) REFERENCES users (id)
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4`,
    `CREATE TABLE IF NOT EXISTS marketplace_model_specs (
      version_id BINARY(16) NOT NULL,
      model_id BINARY(16) NOT NULL,
      display_name VARCHAR(100) NOT NULL,
      description VARCHAR(2000) NOT NULL DEFAULT '',
      prefix_max_bytes INT UNSIGNED NOT NULL DEFAULT 2048,
      max_primary_attempts INT UNSIGNED NOT NULL DEFAULT 0,
      fallback_enabled BOOLEAN NOT NULL DEFAULT TRUE,
      retryable_statuses JSON NOT NULL,
      rate_limit_enabled BOOLEAN NOT NULL DEFAULT FALSE,
      rate_limit_window_millis BIGINT UNSIGNED NULL,
      rate_limit_max_tokens BIGINT UNSIGNED NULL,
      updated_by BINARY(16) NOT NULL,
      updated_at DATETIME(6) NOT NULL,
      PRIMARY KEY (version_id, model_id),
      KEY idx_model_specs_model (model_id, version_id),
      CONSTRAINT chk_model_spec_prefix CHECK (prefix_max_bytes BETWEEN 1 AND 2147483647),
      CONSTRAINT chk_model_spec_attempts CHECK (max_primary_attempts <= 2147483647),
      CONSTRAINT chk_model_spec_rate_limit CHECK (
        (rate_limit_enabled = FALSE AND rate_limit_window_millis IS NULL AND rate_limit_max_tokens IS NULL)
        OR (rate_limit_enabled = TRUE AND rate_limit_window_millis > 0 AND rate_limit_max_tokens IS NOT NULL)
      ),
      CONSTRAINT fk_model_spec_version FOREIGN KEY (version_id) REFERENCES configuration_versions (id),
      CONSTRAINT fk_model_spec_model FOREIGN KEY (model_id) REFERENCES marketplace_models (id),
      CONSTRAINT fk_model_spec_updated_by FOREIGN KEY (updated_by) REFERENCES users (id)
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4`,
    `CREATE TABLE IF NOT EXISTS marketplace_model_tags (
      version_id BINARY(16) NOT NULL,
      model_id BINARY(16) NOT NULL,
      tag VARCHAR(32) NOT NULL,
      sort_order SMALLINT UNSIGNED NOT NULL,
      PRIMARY KEY (version_id, model_id, tag),
      UNIQUE KEY uq_model_tag_order (version_id, model_id, sort_order),
      CONSTRAINT fk_model_tag_version FOREIGN KEY (version_id) REFERENCES configuration_versions (id),
      CONSTRAINT fk_model_tag_model FOREIGN KEY (model_id) REFERENCES marketplace_models (id)
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4`,
    `CREATE TABLE IF NOT EXISTS marketplace_providers (
      id BINARY(16) NOT NULL,
      environment_id BINARY(16) NOT NULL,
      provider_name VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      ownership VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      owner_model_id BINARY(16) NULL,
      created_by BINARY(16) NOT NULL,
      created_at DATETIME(6) NOT NULL,
      archived_by BINARY(16) NULL,
      archived_at DATETIME(6) NULL,
      PRIMARY KEY (id),
      UNIQUE KEY uq_marketplace_provider_name (environment_id, provider_name),
      KEY idx_marketplace_providers_environment (environment_id, archived_at, id),
      KEY idx_marketplace_provider_owner (owner_model_id, archived_at),
      CONSTRAINT chk_marketplace_provider_ownership CHECK (ownership IN ('DEDICATED', 'SHARED')),
      CONSTRAINT chk_marketplace_provider_owner CHECK (
        (ownership = 'DEDICATED' AND owner_model_id IS NOT NULL)
        OR (ownership = 'SHARED' AND owner_model_id IS NULL)
      ),
      CONSTRAINT chk_marketplace_provider_name_bytes CHECK (OCTET_LENGTH(provider_name) BETWEEN 1 AND 128),
      CONSTRAINT fk_marketplace_provider_environment FOREIGN KEY (environment_id) REFERENCES environments (id),
      CONSTRAINT fk_marketplace_provider_owner FOREIGN KEY (owner_model_id) REFERENCES marketplace_models (id),
      CONSTRAINT fk_marketplace_provider_created_by FOREIGN KEY (created_by) REFERENCES users (id),
      CONSTRAINT fk_marketplace_provider_archived_by FOREIGN KEY (archived_by) REFERENCES users (id)
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4`,
    `CREATE TABLE IF NOT EXISTS marketplace_provider_specs (
      version_id BINARY(16) NOT NULL,
      provider_id BINARY(16) NOT NULL,
      display_name VARCHAR(100) NOT NULL,
      base_url VARCHAR(2048) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
      updated_by BINARY(16) NOT NULL,
      updated_at DATETIME(6) NOT NULL,
      PRIMARY KEY (version_id, provider_id),
      KEY idx_provider_specs_provider (provider_id, version_id),
      CONSTRAINT fk_provider_spec_version FOREIGN KEY (version_id) REFERENCES configuration_versions (id),
      CONSTRAINT fk_provider_spec_provider FOREIGN KEY (provider_id) REFERENCES marketplace_providers (id),
      CONSTRAINT fk_provider_spec_updated_by FOREIGN KEY (updated_by) REFERENCES users (id)
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4`,
    `CREATE TABLE IF NOT EXISTS marketplace_model_provider_bindings (
      version_id BINARY(16) NOT NULL,
      model_id BINARY(16) NOT NULL,
      provider_id BINARY(16) NOT NULL,
      route_role VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      sort_order SMALLINT UNSIGNED NOT NULL,
      fallback_slot TINYINT GENERATED ALWAYS AS (CASE WHEN route_role = 'FALLBACK' THEN 1 ELSE NULL END) STORED,
      PRIMARY KEY (version_id, model_id, provider_id),
      UNIQUE KEY uq_model_provider_order (version_id, model_id, route_role, sort_order),
      UNIQUE KEY uq_model_single_fallback (version_id, model_id, fallback_slot),
      KEY idx_model_provider_provider (version_id, provider_id, model_id),
      CONSTRAINT chk_model_provider_role CHECK (route_role IN ('PRIMARY', 'FALLBACK')),
      CONSTRAINT chk_model_provider_fallback_order CHECK (route_role = 'PRIMARY' OR sort_order = 0),
      CONSTRAINT fk_model_provider_version FOREIGN KEY (version_id) REFERENCES configuration_versions (id),
      CONSTRAINT fk_model_provider_model FOREIGN KEY (model_id) REFERENCES marketplace_models (id),
      CONSTRAINT fk_model_provider_provider FOREIGN KEY (provider_id) REFERENCES marketplace_providers (id)
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4`,
    `CREATE TABLE IF NOT EXISTS marketplace_provider_protocols (
      version_id BINARY(16) NOT NULL,
      provider_id BINARY(16) NOT NULL,
      protocol_type VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      request_path VARCHAR(2048) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
      upstream_model_name VARCHAR(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
      updated_by BINARY(16) NOT NULL,
      updated_at DATETIME(6) NOT NULL,
      PRIMARY KEY (version_id, provider_id, protocol_type),
      KEY idx_provider_protocol_provider (provider_id, version_id),
      CONSTRAINT chk_provider_protocol_type CHECK (protocol_type IN ('OPENAI_CHAT_COMPLETIONS', 'ANTHROPIC_MESSAGES')),
      CONSTRAINT chk_provider_protocol_path CHECK (LEFT(request_path, 1) = '/'),
      CONSTRAINT chk_provider_protocol_model CHECK (OCTET_LENGTH(upstream_model_name) > 0),
      CONSTRAINT fk_provider_protocol_version FOREIGN KEY (version_id) REFERENCES configuration_versions (id),
      CONSTRAINT fk_provider_protocol_provider FOREIGN KEY (provider_id) REFERENCES marketplace_providers (id),
      CONSTRAINT fk_provider_protocol_updated_by FOREIGN KEY (updated_by) REFERENCES users (id)
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4`,
    `CREATE TABLE IF NOT EXISTS marketplace_provider_tokens (
      id BINARY(16) NOT NULL,
      environment_id BINARY(16) NOT NULL,
      provider_id BINARY(16) NOT NULL,
      token_name VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
      created_by BINARY(16) NOT NULL,
      created_at DATETIME(6) NOT NULL,
      retired_by BINARY(16) NULL,
      retired_at DATETIME(6) NULL,
      PRIMARY KEY (id),
      UNIQUE KEY uq_provider_token_name (provider_id, token_name),
      KEY idx_provider_tokens_environment (environment_id, provider_id, retired_at),
      CONSTRAINT chk_provider_token_name CHECK (CHAR_LENGTH(token_name) BETWEEN 1 AND 128),
      CONSTRAINT fk_provider_token_environment FOREIGN KEY (environment_id) REFERENCES environments (id),
      CONSTRAINT fk_provider_token_provider FOREIGN KEY (provider_id) REFERENCES marketplace_providers (id),
      CONSTRAINT fk_provider_token_created_by FOREIGN KEY (created_by) REFERENCES users (id),
      CONSTRAINT fk_provider_token_retired_by FOREIGN KEY (retired_by) REFERENCES users (id)
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4`,
    `CREATE TABLE IF NOT EXISTS marketplace_provider_token_specs (
      version_id BINARY(16) NOT NULL,
      token_id BINARY(16) NOT NULL,
      provider_id BINARY(16) NOT NULL,
      secret_id BINARY(16) NOT NULL,
      fingerprint_suffix CHAR(6) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      updated_by BINARY(16) NOT NULL,
      updated_at DATETIME(6) NOT NULL,
      PRIMARY KEY (version_id, token_id),
      KEY idx_token_specs_provider (version_id, provider_id, token_id),
      KEY idx_token_specs_secret (secret_id, version_id),
      CONSTRAINT fk_token_spec_version FOREIGN KEY (version_id) REFERENCES configuration_versions (id),
      CONSTRAINT fk_token_spec_token FOREIGN KEY (token_id) REFERENCES marketplace_provider_tokens (id),
      CONSTRAINT fk_token_spec_provider FOREIGN KEY (provider_id) REFERENCES marketplace_providers (id),
      CONSTRAINT fk_token_spec_secret FOREIGN KEY (secret_id) REFERENCES managed_secrets (id),
      CONSTRAINT fk_token_spec_updated_by FOREIGN KEY (updated_by) REFERENCES users (id)
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4`,
    `CREATE TABLE IF NOT EXISTS marketplace_model_user_groups (
      version_id BINARY(16) NOT NULL,
      model_id BINARY(16) NOT NULL,
      user_group_id BINARY(16) NOT NULL,
      user_group_name VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      PRIMARY KEY (version_id, model_id, user_group_id),
      UNIQUE KEY uq_model_user_group_name (version_id, model_id, user_group_name),
      KEY idx_model_user_groups_group (version_id, user_group_id, model_id),
      CONSTRAINT fk_model_user_group_version FOREIGN KEY (version_id) REFERENCES configuration_versions (id),
      CONSTRAINT fk_model_user_group_model FOREIGN KEY (model_id) REFERENCES marketplace_models (id)
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4`,
    `CREATE TABLE IF NOT EXISTS model_marketplace_projections (
      environment_id BINARY(16) NOT NULL,
      view_kind VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      model_id BINARY(16) NOT NULL,
      source_version_id BINARY(16) NOT NULL,
      source_revision BIGINT UNSIGNED NOT NULL,
      logical_model_name VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      display_name VARCHAR(100) NOT NULL,
      description_excerpt VARCHAR(300) NOT NULL DEFAULT '',
      openai_coverage VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      anthropic_coverage VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      provider_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,
      configured_token_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,
      tokenless_provider_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,
      access_mode VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      draft_state VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      publication_state VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      activation_state VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      latest_release_id BINARY(16) NULL,
      latest_release_at DATETIME(6) NULL,
      validation_error_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,
      validation_warning_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,
      updated_at DATETIME(6) NOT NULL,
      PRIMARY KEY (environment_id, view_kind, model_id),
      KEY idx_model_projection_page (environment_id, view_kind, updated_at, model_id),
      KEY idx_model_projection_name (environment_id, view_kind, logical_model_name, model_id),
      CONSTRAINT chk_model_projection_view CHECK (view_kind IN ('ADMIN_DRAFT', 'PUBLISHED')),
      CONSTRAINT fk_model_projection_environment FOREIGN KEY (environment_id) REFERENCES environments (id),
      CONSTRAINT fk_model_projection_model FOREIGN KEY (model_id) REFERENCES marketplace_models (id),
      CONSTRAINT fk_model_projection_version FOREIGN KEY (source_version_id) REFERENCES configuration_versions (id)
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4`,
    `CREATE TABLE IF NOT EXISTS marketplace_releases (
      id BINARY(16) NOT NULL,
      environment_id BINARY(16) NOT NULL,
      version_id BINARY(16) NOT NULL,
      release_number BIGINT UNSIGNED NOT NULL,
      workflow_state VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      publication_state VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      activation_state VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      created_by BINARY(16) NOT NULL,
      created_at DATETIME(6) NOT NULL,
      PRIMARY KEY (id),
      UNIQUE KEY uq_marketplace_release_number (environment_id, release_number),
      KEY idx_marketplace_release_latest (environment_id, created_at, id),
      CONSTRAINT fk_marketplace_release_environment FOREIGN KEY (environment_id) REFERENCES environments (id),
      CONSTRAINT fk_marketplace_release_version FOREIGN KEY (version_id) REFERENCES configuration_versions (id),
      CONSTRAINT fk_marketplace_release_created_by FOREIGN KEY (created_by) REFERENCES users (id)
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4`,
    `CREATE TABLE IF NOT EXISTS marketplace_release_resources (
      id BINARY(16) NOT NULL,
      release_id BINARY(16) NOT NULL,
      resource_kind VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      group_name VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      data_id VARCHAR(256) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      dependency_order SMALLINT UNSIGNED NOT NULL,
      resource_state VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      old_safe_digest CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
      new_safe_digest CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
      old_md5 CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NULL,
      new_md5 CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NULL,
      content_bytes BIGINT UNSIGNED NULL,
      error_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
      safe_error_message VARCHAR(500) NULL,
      retry_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,
      started_at DATETIME(6) NULL,
      finished_at DATETIME(6) NULL,
      PRIMARY KEY (id),
      UNIQUE KEY uq_release_resource_data_id (release_id, group_name, data_id),
      KEY idx_release_resource_order (release_id, dependency_order, id),
      CONSTRAINT chk_release_resource_kind CHECK (resource_kind IN ('PROVIDER', 'MODELS')),
      CONSTRAINT chk_release_resource_state CHECK (
        resource_state IN ('PENDING', 'WRITING', 'PUBLISHED', 'FAILED', 'SKIPPED')
      ),
      CONSTRAINT fk_release_resource_release FOREIGN KEY (release_id) REFERENCES marketplace_releases (id)
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4`,
    `CREATE TABLE IF NOT EXISTS marketplace_release_instance_results (
      release_id BINARY(16) NOT NULL,
      instance_id VARCHAR(256) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      activation_state VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      evidence_kind VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      accepted_identity VARCHAR(256) CHARACTER SET ascii COLLATE ascii_bin NULL,
      safe_error_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
      observed_at DATETIME(6) NULL,
      PRIMARY KEY (release_id, instance_id),
      CONSTRAINT chk_release_instance_activation CHECK (
        activation_state IN ('UNKNOWN', 'PENDING', 'EFFECTIVE', 'REJECTED')
      ),
      CONSTRAINT fk_release_instance_release FOREIGN KEY (release_id) REFERENCES marketplace_releases (id)
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4`,
  ],
} as const
